### ISSUE TITLE
How to use new version of fontawesome

### ISSUE THREAD

**Issue by dmial** [enten/hyde-y#44]
Hi.

I'd like to use new icon: https://fontawesome.com/icons/telegram?style=brands

It's absent from fontawesome version used by the theme.

I do the following.

0. Set up some fontawesome social icons to play around. All works good.

1. Add in head-extra.html the line:

`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">`

2. Delete in imports.html the line:

`<link rel="stylesheet" href="{{ "css/font-awesome.min.css" | relURL }}">`

3. Play with facebook.html

```
{{ with .Site.Params.facebook }}
<a id="contact-link-facebook" class="contact_link" href="https://www.facebook.com/{{ . }}">
  <span class="fa fa-facebook-square"></span><span>facebook</span></a>
{{ end }}
```

change class to "fab facebook-square", "fab fa-telegram" and etc but icons don't appear. Not new facebook icon, not desired telegram icon.

At the same time this local html file gives me desired effect:
```

<html>
<head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
<i class="fab fa-facebook-square"></i>
<a id="contact-link-facebook" class="contact_link" href="https://www.facebook.com/dima.alexeev">
    <span class="fab fa-telegram"></span></a>
</body>
</html>
```

What may be the problem?

**Comment by enten** [comment]
@dmial 

I think that works.

I checked https://witbit.io/ and I found that [a css rule hide span elements in `.contact_link`](https://github.com/dmial/hyde-wb/blob/71d33d1c41ca837e59214a978bdd3a99cb72a441/scss/_03-modules.less#L139).

```scss
/* ----------------------------- */
/* ==social module               */
/* ----------------------------- */

.contact_link {
  &:hover {
    text-decoration: none;
  }

  &> span {
    display: none; /* remove this line should fixed your issue */
  }

  &> .fa {
    display: inline;
  }
}
```

Is your issue fixed?
